### ISSUE TITLE
Could you please share the Chinese CLIP model used in 「寻隐」？

### ISSUE THREAD

**Issue by DarkTemple** [mazzzystar/Queryable#14]

**Comment by mazzzystar** [comment]
Sorry, I can't do that because I need to adhere to MIT's open-source licensing, and the data used to train the model is not open-source. You can use the script I provided to train your own Chinese model.

**Comment by DarkTemple** [comment]
I currently don't have the GPU computing power to train the model. 
Is there any open source Chinese model you can recommend? Tks.

**Comment by mazzzystar** [comment]
https://github.com/OFA-Sys/Chinese-CLIP
