### ISSUE TITLE
RuntimeError when convert to CoreML model

### ISSUE THREAD

**Issue by DarkTemple** [mazzzystar/Queryable#15]
Hi, I copy and run your PyTorch2CoreML.ipynb code, but get an error when convert to CoreML model.

<img width="1115" alt="image" src="https://github.com/mazzzystar/Queryable/assets/866088/98ec1b2a-e439-4b90-a435-20af3f1cdded">

**Comment by mazzzystar** [comment]
Maybe the issue with pytorch version: https://github.com/mazzzystar/Queryable/issues/9#issuecomment-1633889236

**Comment by OwenHongJinmu** [comment]
try coremltools 7.0b2
