### ISSUE TITLE
Search does not return the correct image when using iCloud Library

### ISSUE THREAD

**Issue by ChrisBDZ** [mazzzystar/Queryable#16]
设备：iPhone 14 Pro (iOS17 beta6 21A5312c)
使用iCloud照片，并且打开了“优化iPhone储存空间”
如图，搜索答非所问，并且无论搜索什么结果都相同
![IMG_4098](https://github.com/mazzzystar/Queryable/assets/67193145/f1e6dc55-7f29-4546-bf7e-2909d4d5d74b)

**Comment by mazzzystar** [comment]
Hi, please refer to this: https://github.com/mazzzystar/Queryable/issues/3#issuecomment-1646891020
