### ISSUE TITLE
CoreMLModels:No such file or directory

### ISSUE THREAD

**Issue by AniOSDeveloper** [mazzzystar/Queryable#2]
After cloning the project to the local environment, the compilation shows a lack of CoreMLModels and Assets files, preventing local execution.
![截屏2023-07-11 13 42 34](https://github.com/mazzzystar/Queryable/assets/14243790/046f8c2b-0eb8-4e17-8295-91aa02df8c23)

**Comment by isgbuddy** [comment]
me 2

**Comment by mazzzystar** [comment]
It might be a issue with the repo structure.

Try delete the folder of `CoreMLModels`, create a new one in your Finder, then put models + .txt/.json files into that folder. And drag that folder into your Xcode structure, remember to choose "Create folder reference", then it should be fine.

<img width="461" alt="image" src="https://github.com/mazzzystar/Queryable/assets/6824141/88d0bbc6-43ad-4a7f-8122-ba1ba7fdbc08">

**Comment by loss99** [comment]
改完之后 fatalError("Fatal error: failed to find the CoreML models.")  PhotoSearcherModel 第19行 报错

**Comment by logtous** [comment]
You need to modify the path of CoreMLModels based on your own situation, as shown in the following figure.
<img width="1399" alt="image" src="https://github.com/mazzzystar/Queryable/assets/88697234/f29eb6ac-f0ab-4d27-b901-368de97a4e1a">
to
<img width="1400" alt="image" src="https://github.com/mazzzystar/Queryable/assets/88697234/561f7486-7030-42d7-b9ae-e516c1ef8e7c">

**Comment by AniOSDeveloper** [comment]
1.CoreMLModels: Open the project and select the red file in the structure, delete it and select 'Remove Reference' in the alert, then drag and drop the CoreMLModels folder from the cloned project to Xcode project, after that you will see a blue folder below Queryable.

2. Assets: select Queryable in the structure, right click and select 'New File...', select and double click 'Asset Catalog', name it Assets and click 'Create'. Then select it and create two 'New Image Assets' named AccentColor and AppIcon. 

After you done the two steps above, the final result will look like the following figure:
![截屏2023-07-11 16 26 43](https://github.com/mazzzystar/Queryable/assets/14243790/2404526f-b688-4d53-b689-2d6b3d402834)

Good luck!

**Comment by mazzzystar** [comment]
> Assets.xcassets needs to be supplemented by the author.

added in this commit: https://github.com/mazzzystar/Queryable/commit/738fcac880d44d1961186d77de9b8709f2863d51

**Comment by andforce** [comment]
https://github.com/mazzzystar/Queryable/pull/8
fixed by above pr.
