### ISSUE TITLE
Feature: Image Library Auto Indexing

### ISSUE THREAD

**Issue by imalkaid** [mazzzystar/Queryable#25]
The current version only creates an index during the first import. It does not update the index database when album pictures are updated, and only does so after uninstalling and reinstalling. It is necessary to add a feature for manual or automatic indexing

**Comment by mazzzystar** [comment]
Firstly, you can perform a search, and then at the bottom of the search box, you'll see a button that says 'New photos available for indexing.' Clicking it will update the index.

The reason why 'updating the index for each photo' is not supported is that loading the model is too slow. The time it takes to load the model once could be used to build an index for 1000 photos.
