### ISSUE TITLE
实在无法注册一个Google账户，每次都被封，请问能不能给一个安卓版apk文件？

### ISSUE THREAD

**Issue by linglongyoudoufu** [mazzzystar/Queryable#38]

**Comment by mazzzystar** [comment]
Andriod版本作者是这个：https://github.com/greyovo/PicQuery

**Comment by linglongyoudoufu** [comment]
谢谢
&nbsp;


霞幕倾松风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ke ***@***.***&gt;; 
发送时间: 2024年2月19日(星期一) 中午11:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mazzzystar/Queryable] 实在无法注册一个Google账户，每次都被封，请问能不能给一个安卓版apk文件？ (Issue #38)





 
Andriod版本作者是这个：https://github.com/greyovo/PicQuery
 
&mdash;
