### ISSUE TITLE
尝试删除照片并拒绝后，使用上拉搜索图片的功能会导致应用闪退

### ISSUE THREAD

**Issue by amamiya-myun** [mazzzystar/Queryable#43]
### 复现步骤

1. 点开一张照片并尝试删除
2. 在对话框中拒绝
3. 上拉搜索图片

（这里是实际操作的视频）https://github.com/user-attachments/assets/d33b2d27-922c-4788-9cd1-86246661a45e

### 设备信息 

- 寻隐版本：1.3.3
- iOS 版本：16.5
- 设备型号：iPhone 13 mini

希望这个小问题能尽快修复，谢谢啦

**Comment by mazzzystar** [comment]
感谢反馈，我试试看！

**Comment by amamiya-myun** [comment]
看这个是修好了，我把这个关啦
