### ISSUE TITLE
Can Queryable bring me to the original image on my device?

### ISSUE THREAD

**Issue by matthewkrieger** [mazzzystar/Queryable#44]
Once Queryable returns search results can I somehow identify the exact photo on my device that it found? For example I’d like to go to the original photo and annotate it

**Comment by mazzzystar** [comment]
Sorry, Apple prohibits third-party apps from directly jumping to the system photo library. Currently, the only method is to manually locate the photo in the album based on the date information provided in the photo details page in Queryable.
