### ISSUE TITLE
在非最右侧开始右滑会导致闪退

### ISSUE THREAD

**Issue by amamiya-myun** [mazzzystar/Queryable#49]
### 复现步骤

1. 随便搜一张图片并点开它
2. 在非最右侧开始右滑

### 设备信息 

- 寻隐版本：1.4.0
- iOS 版本：16.5
- 设备型号：iPhone 13 mini

这次视频传不上来，还是谢谢啦
其他方向似乎没有问题

**Comment by mazzzystar** [comment]
感谢！我复现了，下个版本会修复。

**Comment by mazzzystar** [comment]
最新版本已经修复～

**Comment by amamiya-myun** [comment]
好的喵，我关了
