### ISSUE TITLE
Abnormal operation on A12 and lower chips

### ISSUE THREAD

**Issue by mazzzystar** [mazzzystar/Queryable#5]
Currently, Queryable does not support devices below the iPhone 11 (with the A13 chip). On these devices, indexing can be built normally, but the search results for any query are the same, and I haven't debugged the problem. If you find a solution, I would greatly appreciate it if you could submit a PR.

**Comment by codingstyle** [comment]
Hi,
I managed to make the project work on an iPhone X.
On the TextEncoder init, you need to add the following line to force CPU only on older iPhones.
```
config.computeUnits = .cpuOnly
```

Based on information found here: 
- https://apple.github.io/coremltools/docs-guides/source/faqs.html#error-in-declaring-network-or-computing-nn-outputs
- https://apple.github.io/coremltools/docs-guides/source/load-and-convert-model.html#set-the-compute-units

**Comment by mazzzystar** [comment]
Wow! Do we need to use `if/else` to handle different iPhone devices? Or, if we change this line, would it affect the newer iPhone perfomance?
```
config.computeUnits = .cpuOnly
```

BTW, it would be nice if you could submit a PR to fix the issue : )
