### ISSUE TITLE
Provide the `.mlmodel` / `.mlpackage` files instead of the `.mlmodelc` ones

### ISSUE THREAD

**Issue by laclouis5** [mazzzystar/Queryable#7]
Currently only the compiled CoreML models (`.mlmodelc` files) are provided in the Google Drive. Providing the `.mlmodel` or even better the `.mlpackage` files would be great since this would allow tweaking the network and playing with quantification options.

**Comment by mazzzystar** [comment]
Good point, the `.mlpackage` file has now been [added](https://drive.google.com/drive/folders/12ze3UcqrXt9qeySGh_j_zWE-PWRDTzJv?usp=drive_link).

**Comment by laclouis5** [comment]
One last request, could you share the PyTorch checkpoints / weights of the two models, i.e. the `.pt` or `.pth` files?

**Comment by mazzzystar** [comment]
Here it is: [Queryable#core-ml-export](https://github.com/mazzzystar/Queryable#core-ml-export). The model ckpt is from [CLIP ViT-B/32](https://github.com/openai/CLIP), and I seperated the TextEncoder and ImageEncoder and exported them.
